"use client";
import "./globals.css";
import { Provider } from 'react-redux';
import { store } from '@/store';
import { ThemeProvider, CssBaseline } from '@mui/material';
import theme from '@/theme/theme';
import AuthGuard from "@/components/auth/auth-guard";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <Provider store={store}>
      <ThemeProvider theme={theme}>
        <CssBaseline /> 
        <html lang="en">
          <body><AuthGuard>{children}</AuthGuard></body>
        </html>
      </ThemeProvider>
    </Provider>
  );
}